# Generated by Django 3.2.8 on 2022-09-29 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=100, verbose_name='住客姓名')),
                ('sid', models.CharField(default='', max_length=18, verbose_name='身份证号码')),
                ('face_id', models.CharField(default='', max_length=10, null=True, verbose_name='人脸ID')),
                ('sex', models.CharField(default='', max_length=10, verbose_name='性别')),
                ('live_time', models.DateTimeField(auto_now_add=True, verbose_name='创到店时间')),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='', max_length=50, verbose_name='房间名')),
                ('price', models.IntegerField(default=0, verbose_name='房间价格')),
                ('room_type', models.CharField(default='大床房', max_length=50, verbose_name='房间类别')),
                ('image', models.CharField(default='static/media/default.png', max_length=255, verbose_name='图片')),
                ('status', models.CharField(default='', max_length=50, verbose_name='状态')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('description', models.TextField(default='', verbose_name='房间描述')),
            ],
            options={
                'db_table': 'room',
            },
        ),
        migrations.CreateModel(
            name='WarningInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('count', models.IntegerField(default=1, verbose_name='警告次数')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.room', verbose_name='关联房间')),
            ],
            options={
                'db_table': 'warning_info',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField(help_text='入住时间', max_length=100)),
                ('end_time', models.DateTimeField(auto_now=True, help_text='退房时间')),
                ('status', models.IntegerField(default=1, verbose_name='入住状态,1为在住，0为结束')),
                ('customer', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.customer', verbose_name='关联顾客')),
                ('room', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='app.room', verbose_name='关联房间')),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
