# Generated by Django 3.2.8 on 2022-09-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='live_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='到店时间'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='sid',
            field=models.CharField(default='', max_length=50, verbose_name='身份证号码'),
        ),
    ]
