# Generated by Django 3.2.8 on 2022-09-30 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220929_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_ruzhu',
            field=models.IntegerField(default=0),
        ),
    ]
