# Generated by Django 3.2.8 on 2022-10-01 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer_is_ruzhu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Face',
            fields=[
                ('id', models.CharField(default='', max_length=255, primary_key=True, serialize=False, verbose_name='')),
                ('name', models.CharField(default='', max_length=255, verbose_name='')),
                ('face_feature', models.CharField(default='', max_length=1000, verbose_name='')),
            ],
        ),
    ]
