# Generated by Django 3.2.8 on 2022-10-01 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_face'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='face',
            table='face',
        ),
    ]
